import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import TextIO

from openai import OpenAIError

from artifact_writer import (
    WrittenArtifact,
    write_orchestration_artifacts,
    write_research_report_artifact,
)
from parser.intent_parser import IntentParserError, parse_research_intent
from orchestrator import (
    ClarificationAnswer,
    ClarificationRequest,
    OrchestrationResult,
    OrchestrationStatus,
    continue_research_flow,
    prepare_intent_for_design,
    refine_intent_with_clarifications,
)
from research_report import generate_research_report
from designer.research_designer import ResearchDesignerError


MAX_CLARIFICATION_ROUNDS = 3
DEFAULT_ARTIFACT_DIR = "artifacts/latest_run"
DEFAULT_DATASET_OUTPUT_DIR = "artifacts/generated_dataset"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the ECOS AI Assistant prototype from natural-language request to build artifacts."
    )
    parser.add_argument("query", nargs="*", help="Natural-language research request.")
    parser.add_argument(
        "--provider",
        choices=["qwen", "yandex"],
        default=None,
        help="Override LLM_PROVIDER from .env.",
    )
    parser.add_argument(
        "--model",
        default=None,
        help="Override provider model from .env.",
    )
    parser.add_argument(
        "--design",
        action="store_true",
        help="Deprecated: research design is generated by default.",
    )
    parser.add_argument(
        "--use-defaults",
        action="store_true",
        help="Use safe default assumptions when the parser provided them instead of asking interactively.",
    )
    parser.add_argument(
        "--no-registry",
        action="store_true",
        help="Skip local RAG/catalog lookup and build a fallback source plan.",
    )
    parser.add_argument(
        "--artifact-dir",
        default=DEFAULT_ARTIFACT_DIR,
        help=(
            "Directory where intermediate artifacts and the generated build script "
            f"should be written. Default: {DEFAULT_ARTIFACT_DIR}."
        ),
    )
    parser.add_argument(
        "--no-artifacts",
        action="store_true",
        help="Do not write research artifacts. Mostly useful for parser/debug runs.",
    )
    parser.add_argument(
        "--run-build",
        action="store_true",
        default=True,
        help="Run the generated build script to create target dataset files. Enabled by default.",
    )
    parser.add_argument(
        "--no-run-build",
        dest="run_build",
        action="store_false",
        help="Write artifacts and build script, but do not run the build script.",
    )
    parser.add_argument(
        "--dataset-output-dir",
        default=DEFAULT_DATASET_OUTPUT_DIR,
        help="Directory where the generated build script writes target_dataset.csv and metadata.",
    )
    parser.add_argument(
        "--no-root-build-script",
        dest="write_root_build_script",
        action="store_false",
        help="Do not mirror latest build_target_dataset.py into the project root.",
    )
    parser.add_argument(
        "--output-format",
        choices=["json", "markdown"],
        default="json",
        help="CLI output format. JSON stays machine-readable; markdown mirrors 00_research_report.md.",
    )
    parser.add_argument(
        "--prepare-catalog",
        action="store_true",
        help="Extract dumps if needed and build local catalog_records, catalog_documents and BM25 index before running.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    query = " ".join(args.query).strip()
    if not query:
        query = input("Опишите исследовательскую задачу: ").strip()

    try:
        catalog_stats = None
        if args.prepare_catalog:
            from local_catalog import prepare_local_catalog

            catalog_stats = prepare_local_catalog()

        result = run_interactive_research_flow(
            query,
            provider=args.provider,
            model=args.model,
            use_defaults=args.use_defaults,
            use_registry=not args.no_registry,
        )
        artifact_dir = None if args.no_artifacts else args.artifact_dir
        if args.run_build and artifact_dir is None:
            raise RuntimeError(
                "Нельзя запустить сборку без сохранения артефактов: "
                "уберите --no-artifacts или добавьте --no-run-build."
            )

        artifacts: list[WrittenArtifact] = []
        build_run: dict[str, object] | None = None
        dataset_output_dir = Path(args.dataset_output_dir)
        if artifact_dir:
            artifacts = write_orchestration_artifacts(
                result,
                artifact_dir,
                dataset_output_dir=dataset_output_dir,
            )
            if args.write_root_build_script:
                artifacts.append(_mirror_build_script_to_project_root(artifacts))
        if args.run_build:
            build_run = _run_generated_build_script(
                artifacts=artifacts,
                artifact_dir=Path(artifact_dir or DEFAULT_ARTIFACT_DIR),
                dataset_output_dir=dataset_output_dir,
            )
            if artifact_dir:
                write_research_report_artifact(
                    result,
                    artifact_dir,
                    build_run=build_run,
                    dataset_output_dir=dataset_output_dir,
                )

        if args.output_format == "markdown":
            print(
                generate_research_report(
                    result,
                    build_run=build_run,
                    dataset_output_dir=dataset_output_dir,
                )
            )
        else:
            print(_result_to_json(
                result,
                artifacts=artifacts,
                build_run=build_run,
                catalog_stats=catalog_stats,
            ))
        return
    except (
        RuntimeError,
        IntentParserError,
        ResearchDesignerError,
        ValueError,
        OpenAIError,
    ) as exc:
        print(f"Ошибка: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


def run_interactive_research_flow(
    query: str,
    provider: str | None = None,
    model: str | None = None,
    input_stream: TextIO | None = None,
    error_stream: TextIO | None = None,
    max_clarification_rounds: int = MAX_CLARIFICATION_ROUNDS,
    use_defaults: bool = False,
    use_registry: bool = True,
) -> OrchestrationResult:
    input_stream = input_stream or sys.stdin
    error_stream = error_stream or sys.stderr

    print("запустился 1 этап перевода в формальный запрос", file=error_stream, flush=True)
    intent = parse_research_intent(
        query,
        provider=provider,
        model=model,
    )
    print("завершился 1 этап перевода в формальный запрос", file=error_stream, flush=True)

    for round_number in range(1, max_clarification_rounds + 1):
        readiness = prepare_intent_for_design(intent, use_defaults=use_defaults)
        if readiness.status == OrchestrationStatus.READY_FOR_DESIGN:
            print("запустился 2 этап построения дизайна исследования", file=error_stream, flush=True)
            return continue_research_flow(
                intent,
                provider=provider,
                model=model,
                use_defaults=use_defaults,
                use_registry=use_registry,
            )

        if readiness.status != OrchestrationStatus.NEEDS_CLARIFICATION:
            return readiness

        print(
            f"нужно дозаполнить основной контракт перед 2 этапом "
            f"(раунд {round_number}/{max_clarification_rounds})",
            file=error_stream,
            flush=True,
        )
        answers = _collect_clarification_answers(
            readiness.clarification_requests,
            input_stream=input_stream,
            error_stream=error_stream,
        )
        print("обновляю основной контракт с уточнениями пользователя", file=error_stream, flush=True)
        intent = refine_intent_with_clarifications(
            intent,
            answers,
            provider=provider,
            model=model,
        )

    readiness = prepare_intent_for_design(intent, use_defaults=use_defaults)
    if readiness.status == OrchestrationStatus.READY_FOR_DESIGN:
        print("запустился 2 этап построения дизайна исследования", file=error_stream, flush=True)
        return continue_research_flow(
            intent,
            provider=provider,
            model=model,
            use_defaults=use_defaults,
            use_registry=use_registry,
        )

    missing_fields = ", ".join(request.field for request in readiness.clarification_requests)
    raise RuntimeError(
        "Не удалось дозаполнить основной контракт перед 2 этапом. "
        f"Остались поля: {missing_fields or readiness.status.value}."
    )


def _collect_clarification_answers(
    requests: list[ClarificationRequest],
    input_stream: TextIO,
    error_stream: TextIO,
) -> list[ClarificationAnswer]:
    answers: list[ClarificationAnswer] = []
    for index, request in enumerate(requests, start=1):
        print("", file=error_stream)
        print(f"Уточнение {index}/{len(requests)}: {request.question}", file=error_stream)
        print(f"Поле: {request.field}. Причина: {request.reason}", file=error_stream)
        if request.default_assumption:
            print(
                f"Можно нажать Enter, чтобы использовать default: {request.default_assumption}",
                file=error_stream,
            )

        answer, used_default = _read_required_answer(
            request,
            input_stream=input_stream,
            error_stream=error_stream,
        )
        answers.append(
            ClarificationAnswer(
                field=request.field,
                question=request.question,
                answer=answer,
                used_default=used_default,
            )
        )

    return answers


def _read_required_answer(
    request: ClarificationRequest,
    input_stream: TextIO,
    error_stream: TextIO,
) -> tuple[str, bool]:
    while True:
        print("Ответ: ", end="", file=error_stream, flush=True)
        line = input_stream.readline()
        if line == "":
            raise RuntimeError(
                "Невозможно дозаполнить основной контракт: поток ввода закрыт."
            )

        answer = line.strip()
        if answer:
            return answer, False
        if request.default_assumption:
            return request.default_assumption, True

        print("Ответ обязателен, чтобы перейти ко 2 этапу.", file=error_stream)


def _result_to_json(
    result: OrchestrationResult,
    artifacts: list[WrittenArtifact] | None = None,
    build_run: dict[str, object] | None = None,
    catalog_stats: dict[str, object] | None = None,
) -> str:
    payload = {
        "intent": result.intent.model_dump(mode="json"),
        "research_design": (
            result.research_design.model_dump(mode="json")
            if result.research_design
            else None
        ),
        "dataset_structure": (
            result.dataset_structure.model_dump(mode="json")
            if result.dataset_structure
            else None
        ),
        "build_plan": (
            result.build_plan.model_dump(mode="json")
            if result.build_plan
            else None
        ),
        "build_script": (
            result.build_script.model_dump(mode="json")
            if result.build_script
            else None
        ),
    }
    if result.status != OrchestrationStatus.DESIGN_READY:
        payload["status"] = result.status.value
    if result.message:
        payload["message"] = result.message
    if result.clarification_requests:
        payload["clarification_requests"] = [
            request.model_dump(mode="json")
            for request in result.clarification_requests
        ]
    if artifacts:
        payload["artifacts"] = [
            artifact.model_dump(mode="json")
            for artifact in artifacts
        ]
    if build_run:
        payload["build_run"] = build_run
    if catalog_stats:
        payload["catalog_stats"] = catalog_stats

    return json.dumps(payload, ensure_ascii=False, indent=2)


def _run_generated_build_script(
    artifacts: list[WrittenArtifact],
    artifact_dir: Path,
    dataset_output_dir: Path,
) -> dict[str, object]:
    script_artifact = next(
        (artifact for artifact in artifacts if artifact.artifact_type == "build_script"),
        None,
    )
    if script_artifact is None:
        raise RuntimeError("Нельзя запустить сборку: build_script artifact не был записан.")

    completed = subprocess.run(
        [
            sys.executable,
            script_artifact.path,
            "--output-dir",
            str(dataset_output_dir),
            "--project-root",
            str(Path.cwd()),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    try:
        output = json.loads(completed.stdout)
    except json.JSONDecodeError:
        output = {"stdout": completed.stdout}
    return {
        "returncode": completed.returncode,
        "output": output,
        "stderr": completed.stderr,
    }


def _mirror_build_script_to_project_root(
    artifacts: list[WrittenArtifact],
) -> WrittenArtifact:
    script_artifact = next(
        (artifact for artifact in artifacts if artifact.artifact_type == "build_script"),
        None,
    )
    if script_artifact is None:
        raise RuntimeError("Нельзя записать build_target_dataset.py в корень: build_script artifact не найден.")

    source_path = Path(script_artifact.path)
    root_script_path = Path.cwd() / source_path.name
    root_script_path.write_text(source_path.read_text(encoding="utf-8"), encoding="utf-8")
    return WrittenArtifact(
        artifact_type="root_build_script",
        path=str(root_script_path.resolve()),
    )


if __name__ == "__main__":
    main()
