import argparse
import json
import sys

from openai import OpenAIError

from intent_parser import IntentParserError, parse_research_intent
from research_designer import ResearchDesignerError, design_research


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Parse a research request into JSON.")
    parser.add_argument("query", nargs="*", help="Natural-language research request.")
    parser.add_argument(
        "--provider",
        choices=["qwen", "yandex"],
        default=None,
        help="Override LLM_PROVIDER from .env.",
    )
    parser.add_argument(
        "--model",
        default=None,
        help="Override provider model from .env.",
    )
    parser.add_argument(
        "--design",
        action="store_true",
        help="Deprecated: research design is generated by default.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    query = " ".join(args.query).strip()
    if not query:
        query = input("Опишите исследовательскую задачу: ").strip()

    try:
        print("запустился 1 этап перевода в формальный запрос", file=sys.stderr, flush=True)
        intent = parse_research_intent(
            query,
            provider=args.provider,
            model=args.model,
        )
        print("завершился 1 этап перевода в формальный запрос", file=sys.stderr, flush=True)
        print("запустился 2 этап построения дизайна исследования", file=sys.stderr, flush=True)
        design = design_research(
            intent,
            provider=args.provider,
            model=args.model,
        )
        print(json.dumps(
            {
                "intent": intent.model_dump(mode="json"),
                "research_design": design.model_dump(mode="json"),
            },
            ensure_ascii=False,
            indent=2,
        ))
        return
    except (
        RuntimeError,
        IntentParserError,
        ResearchDesignerError,
        ValueError,
        OpenAIError,
    ) as exc:
        print(f"Ошибка: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()
