import json
import textwrap

from pydantic import BaseModel, ConfigDict, Field, field_validator

from assembly_planner import DatasetBuildPlan
from dataset_structure import TargetDatasetStructure
from parser.intent_parser import none_to_empty_list


class GeneratedBuildScript(BaseModel):
    model_config = ConfigDict(extra="forbid")

    filename: str = "build_target_dataset.py"
    language: str = "python"
    content: str
    usage: str
    produces: list[str] = Field(default_factory=list)

    @field_validator("produces", mode="before")
    @classmethod
    def _none_to_empty_list(cls, value):
        return none_to_empty_list(value)


def generate_build_script(
    structure: TargetDatasetStructure,
    plan: DatasetBuildPlan,
) -> GeneratedBuildScript:
    content = _render_script(structure, plan)
    return GeneratedBuildScript(
        content=content,
        usage=(
            "Скрипт сохраняется в artifacts/latest_run/build_target_dataset.py "
            "и зеркалируется в корень проекта как build_target_dataset.py. "
            "Запуск из корня проекта: python build_target_dataset.py "
            "--output-dir artifacts/generated_dataset"
        ),
        produces=[
            "target_dataset.csv",
            "target_dataset.metadata.json",
            "source_manifest.json",
        ],
    )


def _render_script(
    structure: TargetDatasetStructure,
    plan: DatasetBuildPlan,
) -> str:
    structure_json = json.dumps(
        structure.model_dump(mode="json"),
        ensure_ascii=False,
        indent=2,
    )
    plan_json = json.dumps(
        plan.model_dump(mode="json"),
        ensure_ascii=False,
        indent=2,
    )

    return textwrap.dedent(
        f'''\
        # -*- coding: utf-8 -*-
        """Build script generated by ECOS AI Assistant prototype.

        The script is intentionally readable and conservative:
        - it preserves source lineage in metadata;
        - it reads local CSV/JSON/JSONL predecessors when paths are available;
        - it writes an empty-but-valid target dataset template when source rows are unavailable.
        """

        import argparse
        import csv
        import gzip
        import json
        import re
        from datetime import datetime, timezone
        from pathlib import Path


        TARGET_STRUCTURE = json.loads({structure_json!r})

        BUILD_PLAN = json.loads({plan_json!r})

        GEO_ALIASES = {{
            "россия": ["россия", "российская федерация", "russian federation", "russia"],
            "российская федерация": ["россия", "российская федерация", "russian federation", "russia"],
            "бангладеш": ["бангладеш", "bangladesh", "bgd"],
            "казахстан": ["казахстан", "kazakhstan"],
            "сша": ["сша", "соединенные штаты", "united states"],
            "мир": ["мир", "world"],
        }}


        def parse_args():
            parser = argparse.ArgumentParser(description="Build target dataset from planned predecessors.")
            parser.add_argument("--output-dir", default="artifacts/generated_dataset")
            parser.add_argument("--project-root", default=".")
            parser.add_argument("--strict", action="store_true", help="Fail if no source rows can be read.")
            return parser.parse_args()


        def resolve_data_path(project_root, data_path):
            if not data_path:
                return None
            path = Path(data_path)
            if not path.is_absolute():
                path = Path(project_root) / path
            return path


        def read_source_rows(path):
            if path is None or not path.exists():
                return []
            suffix = path.suffix.lower()
            suffixes = [item.lower() for item in path.suffixes]
            if suffix == ".csv":
                with path.open(newline="", encoding="utf-8-sig") as file:
                    return list(csv.DictReader(file))
            if suffixes[-2:] == [".jsonl", ".gz"]:
                rows = []
                with gzip.open(path, mode="rt", encoding="utf-8") as file:
                    for line in file:
                        if line.strip():
                            rows.append(json.loads(line))
                return rows
            if suffix == ".jsonl":
                rows = []
                with path.open(encoding="utf-8") as file:
                    for line in file:
                        if line.strip():
                            rows.append(json.loads(line))
                return rows
            if suffix == ".json":
                with path.open(encoding="utf-8") as file:
                    payload = json.load(file)
                if isinstance(payload, list):
                    return [row for row in payload if isinstance(row, dict)]
                if isinstance(payload, dict):
                    for value in payload.values():
                        if isinstance(value, list):
                            return [row for row in value if isinstance(row, dict)]
                return []
            if suffix == ".parquet":
                try:
                    import pyarrow.parquet as pq
                except ImportError:
                    return []
                table = pq.read_table(path)
                return [dict(row) for row in table.to_pylist()]
            return []


        def first_non_empty(*values):
            for value in values:
                if value is not None and str(value).strip() != "":
                    return value
            return None


        def clean_cell(value):
            if isinstance(value, str):
                return " ".join(value.split())
            return value


        def column_sort_key(name):
            match = re.search(r"\\d+", str(name))
            return int(match.group(0)) if match else 10_000


        def int_year(value):
            if value is None:
                return None
            if isinstance(value, float) and value.is_integer():
                value = int(value)
            text = str(value).strip()
            if re.fullmatch(r"\\d{{4}}(?:\\.0)?", text):
                year = int(float(text))
                if 1800 <= year <= 2200:
                    return year
            return None


        def normalize_source_rows(rows):
            if not rows:
                return []
            first = rows[0]
            column_keys = sorted(
                [key for key in first if re.fullmatch(r"column\\d+", str(key))],
                key=column_sort_key,
            )
            if not column_keys:
                return rows

            year_columns = []
            dimension_columns = []
            for key in column_keys:
                year = int_year(first.get(key))
                if year is not None:
                    year_columns.append((key, year))
                elif first.get(key):
                    dimension_columns.append((key, str(first[key]).strip()))

            if not year_columns:
                return rows

            normalized = []
            for source_row in rows[1:]:
                base = {{
                    dimension_name: clean_cell(source_row.get(key))
                    for key, dimension_name in dimension_columns
                }}
                for key, year in year_columns:
                    value = source_row.get(key)
                    if value is None or str(value).strip() == "":
                        continue
                    normalized.append({{**base, "year": year, "value": value}})
            return normalized


        def row_year(source_row):
            value = first_non_empty(source_row.get("year"), source_row.get("date"), source_row.get("Год"))
            if value is None:
                return None
            year = int_year(value)
            if year is not None:
                return year
            match = re.search(r"\\d{{4}}", str(value))
            return int(match.group(0)) if match else None


        def target_year_bounds():
            value = TARGET_STRUCTURE.get("time_range") or ""
            years = [int(item) for item in re.findall(r"\\d{{4}}", value)]
            if len(years) >= 2:
                return min(years), max(years)
            if len(years) == 1:
                text = str(value).lower()
                if re.search(r"\\b(до|по|before|until)\\b", text):
                    return None, years[0]
                if re.search(r"\\b(с|from|since|после|after)\\b", text):
                    return years[0], None
                return years[0], years[0]
            return None, None


        def target_years():
            start_year, end_year = target_year_bounds()
            if start_year is None or end_year is None:
                return []
            return list(range(start_year, end_year + 1))


        def source_geo_values(source_row):
            candidates = [
                source_row.get("geo"),
                source_row.get("country_name"),
                source_row.get("country"),
                source_row.get("countryiso3code"),
                source_row.get("region"),
                source_row.get("territory"),
            ]
            for key, value in source_row.items():
                lower_key = str(key).lower()
                if any(token in lower_key for token in ("окато", "территор", "регион", "страна", "субъект")):
                    candidates.append(value)
            return [clean_cell(value) for value in candidates if value is not None and str(value).strip()]


        def source_geo_text(source_row):
            return " ".join(str(value).lower() for value in source_geo_values(source_row))


        def normalize_geo_value(value):
            text = str(value).strip().lower()
            text = re.sub(r"^\\d+\\s+", "", text)
            return " ".join(text.split())


        def geo_matches_target(value, variants):
            normalized_value = normalize_geo_value(value)
            for variant in variants:
                normalized_variant = normalize_geo_value(variant)
                if normalized_value == normalized_variant:
                    return True
            return False


        def target_geo_variants():
            variants = []
            for geo in TARGET_STRUCTURE.get("geography", []):
                normalized = str(geo).strip().lower()
                variants.append(normalized)
                variants.extend(GEO_ALIASES.get(normalized, []))
            return [variant for variant in dict.fromkeys(variants) if variant]


        def row_matches_target(source_row):
            start_year, end_year = target_year_bounds()
            year = row_year(source_row)
            if start_year is not None and year is not None and year < start_year:
                return False
            if end_year is not None and year is not None and year > end_year:
                return False

            variants = target_geo_variants()
            geo_values = source_geo_values(source_row)
            if variants and geo_values:
                if not any(geo_matches_target(value, variants) for value in geo_values):
                    return False
            elif variants and source_geo_text(source_row):
                geo_text = source_geo_text(source_row)
                if not any(variant in geo_text for variant in variants):
                    return False
            if not row_matches_default_totals(source_row):
                return False
            return True


        def row_matches_default_totals(source_row):
            row_grain = str(TARGET_STRUCTURE.get("row_grain") or "").lower()
            includes_sector = any(token in row_grain for token in ("отрасл", "сектор", "activity", "sector"))
            if includes_sector:
                return True
            for key, value in source_row.items():
                lower_key = str(key).lower()
                lower_value = str(value).lower() if value is not None else ""
                if "видов экономической деятельности" in lower_key and "всего" not in lower_value:
                    return False
                if "вид цены" in lower_key and "постоян" in lower_value:
                    return False
            return True


        def value_for_column(column, source_row):
            name = column["name"]
            role = column.get("role")
            source_field = column.get("source_field")
            direct_value = source_row.get(name)
            if direct_value is not None:
                return direct_value
            if source_field and source_field in source_row:
                return source_row[source_field]
            if name == "geo":
                return clean_cell(first_non_empty(
                    source_row.get("geo"),
                    source_row.get("country_name"),
                    source_row.get("country"),
                    source_row.get("region"),
                    source_row.get("Классификатор объектов административно-территориального деления (ОКАТО)"),
                ))
            if name == "year":
                return row_year(source_row)
            if role in ("indicator", "derived_metric"):
                return first_non_empty(source_row.get("value"), source_row.get("Value"), source_row.get("VALUE"))
            return None


        def project_row(source_row, source):
            generated_at = datetime.now(timezone.utc).isoformat()
            row = {{}}
            for column in TARGET_STRUCTURE["columns"]:
                name = column["name"]
                row[name] = value_for_column(column, source_row)
            row["source_name"] = row.get("source_name") or source.get("source_name") or source.get("source")
            row["source_url"] = row.get("source_url") or source.get("source_url")
            row["source_dataset_id"] = row.get("source_dataset_id") or source.get("dataset_id")
            row["downloaded_at"] = row.get("downloaded_at") or generated_at
            return row


        def collect_rows(project_root):
            rows = []
            manifest = []
            for source in BUILD_PLAN.get("predecessor_datasets", []):
                path = resolve_data_path(project_root, source.get("data_path"))
                source_rows = normalize_source_rows(read_source_rows(path))
                matching_rows = [row for row in source_rows if row_matches_target(row)]
                manifest.append({{
                    "title": source.get("title"),
                    "source": source.get("source"),
                    "dataset_id": source.get("dataset_id"),
                    "data_path": str(path) if path else None,
                    "source_url": source.get("source_url"),
                    "rows_read": len(source_rows),
                    "rows_matched": len(matching_rows),
                    "why_selected": source.get("why_selected"),
                    "possible_limitations": source.get("possible_limitations", []),
                }})
                rows.extend(project_row(source_row, source) for source_row in matching_rows)
            return rows, manifest


        def build_coverage(rows):
            requested_years = target_years()
            available_years = sorted({{
                year
                for row in rows
                for year in [row_year(row)]
                if year is not None
            }})
            missing_years = [
                year for year in requested_years
                if year not in available_years
            ] if requested_years else []
            return {{
                "requested_years": requested_years,
                "available_years": available_years,
                "missing_years": missing_years,
                "available_start_year": available_years[0] if available_years else None,
                "available_end_year": available_years[-1] if available_years else None,
            }}


        def write_csv(path, rows):
            fieldnames = [column["name"] for column in TARGET_STRUCTURE["columns"]]
            with path.open("w", newline="", encoding="utf-8") as file:
                writer = csv.DictWriter(file, fieldnames=fieldnames, extrasaction="ignore")
                writer.writeheader()
                writer.writerows(rows)


        def write_json(path, payload):
            with path.open("w", encoding="utf-8") as file:
                json.dump(payload, file, ensure_ascii=False, indent=2)


        def main():
            args = parse_args()
            output_dir = Path(args.output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)
            rows, source_manifest = collect_rows(args.project_root)
            coverage = build_coverage(rows)

            if args.strict and not rows:
                raise SystemExit(
                    "No source rows were read. Check data_path values or run without --strict "
                    "to emit an empty target dataset template."
                )

            dataset_path = output_dir / "target_dataset.csv"
            metadata_path = output_dir / "target_dataset.metadata.json"
            manifest_path = output_dir / "source_manifest.json"

            write_csv(dataset_path, rows)
            write_json(manifest_path, source_manifest)
            write_json(metadata_path, {{
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "row_count": len(rows),
                "coverage": coverage,
                "target_structure": TARGET_STRUCTURE,
                "build_plan": BUILD_PLAN,
                "outputs": {{
                    "dataset": str(dataset_path),
                    "metadata": str(metadata_path),
                    "source_manifest": str(manifest_path),
                }},
            }})

            print(json.dumps({{
                "dataset": str(dataset_path),
                "metadata": str(metadata_path),
                "source_manifest": str(manifest_path),
                "row_count": len(rows),
                "coverage": coverage,
            }}, ensure_ascii=False, indent=2))


        if __name__ == "__main__":
            main()
        '''
    )
